/**
 * MAZE
 * MAZE API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CharacterId } from './characterId';


export interface Character { 
    readonly id?: CharacterId;
    readonly startLocation?: number;
    path?: Array<number>;
    readonly location?: number;
    /**
     * Number of seconds left before dying
     */
    readonly health?: number;
    readonly hasWeapon?: boolean;
    /**
     * Number of seconds before ability can be used
     */
    readonly abilityCooldown?: number;
}

