/**
 * MAZE
 * MAZE API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A character identifier
 */
export type CharacterId = 'mage' | 'theif' | 'warrior' | 'cleric';

export const CharacterId = {
    Mage: 'mage' as CharacterId,
    Theif: 'theif' as CharacterId,
    Warrior: 'warrior' as CharacterId,
    Cleric: 'cleric' as CharacterId
};

