/**
 * MAZE
 * MAZE API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Obstacle { 
    readonly id?: number;
    readonly type?: Obstacle.TypeEnum;
    /**
     * Paths which are blocked by the obstacle
     */
    readonly blockedPaths?: Array<number>;
}
export namespace Obstacle {
    export type TypeEnum = 'forcefield' | 'lock' | 'stone' | 'ghost';
    export const TypeEnum = {
        Forcefield: 'forcefield' as TypeEnum,
        Lock: 'lock' as TypeEnum,
        Stone: 'stone' as TypeEnum,
        Ghost: 'ghost' as TypeEnum
    };
}


